/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class NewJFrame111 extends javax.swing.JFrame {

    private int x, y;
    private User user;
    private ArrayList<User> users;
    private ArrayList<Hospitalization>hospitalizations;
    private ArrayList<Appointment>appointments;
    private Doctor doctor;
    private Patient patient;
    public NewJFrame111(User user,Doctor doc, ArrayList<User> users,ArrayList<Hospitalization> hospitalizations,ArrayList<Appointment> appointments) {
        initComponents();
        this.user = user;
        this.users =users;
        this.doctor = doc;
        this.hospitalizations = hospitalizations;
        this.appointments = appointments;
        if (user instanceof Administrator)
            lblBack.setVisible(true);
        else    
            lblBack.setVisible(false);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new packagee.PanelRound();
        panelRound2 = new packagee.PanelRound();
        btnX = new javax.swing.JButton();
        lblDoctorView = new javax.swing.JLabel();
        lblBack = new javax.swing.JButton();
        tabAppointments = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        radTotalApp = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTotalApp = new javax.swing.JTable();
        radioPendingApp = new javax.swing.JRadioButton();
        jButton12 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cboPatient = new javax.swing.JComboBox<>();
        lblPatient = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblFirstname = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        lblSpecialty = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JTextField();
        lblAssignedOffice = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtAssignedOffice = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblPasswordConfirm = new javax.swing.JLabel();
        txtPasswordConfirm = new javax.swing.JTextField();
        cboSpecialty = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblAppID = new javax.swing.JLabel();
        lblAMA = new javax.swing.JLabel();
        cboAppID = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnAccept = new javax.swing.JButton();
        lblRMA = new javax.swing.JLabel();
        lblAppointment = new javax.swing.JLabel();
        cboAppointment = new javax.swing.JComboBox<>();
        btnAccept2 = new javax.swing.JButton();
        lblNewTimeApp = new javax.swing.JLabel();
        txtNewTimeApp = new javax.swing.JTextField();
        lblReasonForApp = new javax.swing.JLabel();
        txtReasonForApp = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblCMA = new javax.swing.JLabel();
        lblAppointment2 = new javax.swing.JLabel();
        cboAppointment2 = new javax.swing.JComboBox<>();
        lblDiagnosis = new javax.swing.JLabel();
        lblObservations = new javax.swing.JLabel();
        lblRT = new javax.swing.JLabel();
        lblFuIndication = new javax.swing.JLabel();
        btnComplete = new javax.swing.JButton();
        lblHospitalization = new javax.swing.JLabel();
        lblRFHospitalization = new javax.swing.JLabel();
        lblDateofEntry = new javax.swing.JLabel();
        txtDateOfEntry = new javax.swing.JTextField();
        lblEstimatedDuration = new javax.swing.JLabel();
        txtEstimatedDuration = new javax.swing.JTextField();
        lblObservations2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaObservations2 = new javax.swing.JTextArea();
        btnGenerate = new javax.swing.JButton();
        cboRequests = new javax.swing.JComboBox<>();
        radRequests = new javax.swing.JRadioButton();
        radPatientID = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtaDiagnosis = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtaObservations = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtaRT = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtaFuIndication = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JButton();
        cboPatientID = new javax.swing.JComboBox<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtaRFHospitalization = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lblAppointmentID = new javax.swing.JLabel();
        lblMedicationName = new javax.swing.JLabel();
        txtMedicationName = new javax.swing.JTextField();
        lblDose = new javax.swing.JLabel();
        txtDose = new javax.swing.JTextField();
        lblAdministrationRoute = new javax.swing.JLabel();
        txtAdministrationRoute = new javax.swing.JTextField();
        lblFrecuency = new javax.swing.JLabel();
        txtFrecuency = new javax.swing.JTextField();
        lblTreatmentDuration = new javax.swing.JLabel();
        txtTreatmentDuration = new javax.swing.JTextField();
        lblAdditionalInstructions = new javax.swing.JLabel();
        txtAdditionalInstructions = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabPrescribeMedications = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnPrescribe = new javax.swing.JButton();
        cboApoointmentID = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setRadius(50);

        panelRound2.setRadius(50);
        panelRound2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        btnX.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnX.setText("X");
        btnX.setBorderPainted(false);
        btnX.setContentAreaFilled(false);
        btnX.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnX.setFocusable(false);
        btnX.setRequestFocusEnabled(false);
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        lblDoctorView.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblDoctorView.setText("DOCTOR VIEW");

        lblBack.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblBack.setText("Back");
        lblBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDoctorView)
                .addGap(32, 32, 32)
                .addComponent(lblBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnX)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDoctorView, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblBack))
        );

        radTotalApp.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        radTotalApp.setText("Total appointments");
        radTotalApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTotalAppActionPerformed(evt);
            }
        });

        tableTotalApp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Patient", "Specialty", "Type", "Status"
            }
        ));
        jScrollPane3.setViewportView(tableTotalApp);

        radioPendingApp.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        radioPendingApp.setText("Pending appointments");
        radioPendingApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPendingAppActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jButton12.setText("Logout");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton12)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(radTotalApp)
                            .addGap(18, 18, 18)
                            .addComponent(radioPendingApp))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radTotalApp)
                    .addComponent(radioPendingApp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(23, 23, 23))
        );

        tabAppointments.addTab("Appointments visualization", jPanel4);

        cboPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatient.setText("Patient");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jButton8.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblPatient)
                        .addGap(18, 18, 18)
                        .addComponent(cboPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(601, 601, 601))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatient)
                    .addComponent(cboPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton8)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        tabAppointments.addTab("History Appointments of a patient", jPanel5);

        lblFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblFirstname.setText("Firstname");

        txtFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLastname.setText("Lastname");

        txtLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblSpecialty.setText("Specialty");

        lblLicenseNumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLicenseNumber.setText("License Number");

        txtLicenseNumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblAssignedOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAssignedOffice.setText("Assigned office");

        txtUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("User");

        txtAssignedOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Password");

        lblPasswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPasswordConfirm.setText("Password confirmation");

        txtPasswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        cboSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        btnSave.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(lblFirstname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblLastname)
                        .addGap(18, 18, 18)
                        .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSpecialty)
                        .addGap(18, 18, 18)
                        .addComponent(cboSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(lblLicenseNumber)
                        .addGap(18, 18, 18)
                        .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAssignedOffice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAssignedOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(lblPasswordConfirm))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(btnSave))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addComponent(txtPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstname)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastname)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpecialty)
                    .addComponent(cboSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNumber)
                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAssignedOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAssignedOffice))
                .addGap(30, 30, 30)
                .addComponent(lblUser)
                .addGap(18, 18, 18)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addGap(27, 27, 27)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPasswordConfirm)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSave)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        tabAppointments.addTab("Modify info", jPanel3);

        lblAppID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppID.setText("Appointment ID");

        lblAMA.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAMA.setText("Accept medical appointment");

        cboAppID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboAppID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAccept.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        lblRMA.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRMA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRMA.setText("Reschedule medical appointment");

        lblAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointment.setText("Appointment");

        cboAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboAppointment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        btnAccept2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnAccept2.setText("Accept");
        btnAccept2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccept2ActionPerformed(evt);
            }
        });

        lblNewTimeApp.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblNewTimeApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewTimeApp.setText("New time appointment");

        txtNewTimeApp.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblReasonForApp.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblReasonForApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReasonForApp.setText("Reason for appointment");

        txtReasonForApp.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblCMA.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblCMA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCMA.setText("Complete medical appointment");

        lblAppointment2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointment2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointment2.setText("Appointment");

        cboAppointment2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboAppointment2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblDiagnosis.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDiagnosis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiagnosis.setText("Diagnosis");

        lblObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblObservations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObservations.setText("Observations");

        lblRT.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRT.setText("Recommended treatment");

        lblFuIndication.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblFuIndication.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuIndication.setText("Follow-up indication");

        btnComplete.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        lblHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalization.setText("Hospitalization");

        lblRFHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRFHospitalization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRFHospitalization.setText("Reason for hospitalization");

        lblDateofEntry.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDateofEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateofEntry.setText("Date of entry");

        txtDateOfEntry.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblEstimatedDuration.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblEstimatedDuration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstimatedDuration.setText("Estimated duration");

        txtEstimatedDuration.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblObservations2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblObservations2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObservations2.setText("Observations");

        txtaObservations2.setColumns(20);
        txtaObservations2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtaObservations2.setRows(5);
        jScrollPane1.setViewportView(txtaObservations2);

        btnGenerate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        cboRequests.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboRequests.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        radRequests.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        radRequests.setText("Requests");

        radPatientID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        radPatientID.setText("Patient ID");

        txtaDiagnosis.setColumns(20);
        txtaDiagnosis.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtaDiagnosis.setRows(5);
        jScrollPane6.setViewportView(txtaDiagnosis);

        txtaObservations.setColumns(20);
        txtaObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtaObservations.setRows(5);
        jScrollPane7.setViewportView(txtaObservations);

        txtaRT.setColumns(20);
        txtaRT.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtaRT.setRows(5);
        jScrollPane8.setViewportView(txtaRT);

        txtaFuIndication.setColumns(20);
        txtaFuIndication.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtaFuIndication.setRows(5);
        jScrollPane9.setViewportView(txtaFuIndication);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnCancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cboPatientID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboPatientID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        txtaRFHospitalization.setColumns(20);
        txtaRFHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtaRFHospitalization.setRows(5);
        jScrollPane10.setViewportView(txtaRFHospitalization);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAccept)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cboAppID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67))))
                            .addComponent(lblAppID, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblAMA)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRMA, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblAppointment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNewTimeApp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblReasonForApp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(cboAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(txtNewTimeApp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(txtReasonForApp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(btnAccept2)))
                            .addGap(91, 91, 91))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnComplete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAppointment2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCMA, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(cboAppointment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDiagnosis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblObservations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblFuIndication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRT, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHospitalization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDateofEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEstimatedDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblObservations2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDateOfEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstimatedDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGenerate))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cboRequests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(radRequests)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(radPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cboPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRFHospitalization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblCMA)
                        .addGap(10, 10, 10)
                        .addComponent(lblAppointment2)
                        .addGap(18, 18, 18)
                        .addComponent(cboAppointment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDiagnosis)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblObservations)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRT)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFuIndication)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComplete)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblAMA)
                                .addGap(18, 18, 18)
                                .addComponent(lblAppID)
                                .addGap(18, 18, 18)
                                .addComponent(cboAppID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnAccept))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblRMA)
                                .addGap(18, 18, 18)
                                .addComponent(lblAppointment)
                                .addGap(18, 18, 18)
                                .addComponent(cboAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNewTimeApp)
                                .addGap(18, 18, 18)
                                .addComponent(txtNewTimeApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblReasonForApp)
                                .addGap(18, 18, 18)
                                .addComponent(txtReasonForApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnAccept2)))
                        .addGap(18, 18, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblHospitalization)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radRequests)
                    .addComponent(radPatientID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboRequests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblRFHospitalization)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDateofEntry)
                .addGap(18, 18, 18)
                .addComponent(txtDateOfEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEstimatedDuration)
                .addGap(18, 18, 18)
                .addComponent(txtEstimatedDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblObservations2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerate)
                    .addComponent(btnCancel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        tabAppointments.addTab("Request/Appointments", jPanel1);

        lblAppointmentID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentID.setText("Appointment ID");

        lblMedicationName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblMedicationName.setText("Medication name");

        txtMedicationName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDose.setText("Dose");

        txtDose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblAdministrationRoute.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAdministrationRoute.setText("Administration route");

        txtAdministrationRoute.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblFrecuency.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblFrecuency.setText("Frecuency");

        txtFrecuency.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblTreatmentDuration.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblTreatmentDuration.setText("Treatment duration");

        txtTreatmentDuration.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblAdditionalInstructions.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAdditionalInstructions.setText("Additional instructions");

        txtAdditionalInstructions.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        tabPrescribeMedications.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Medication name", "Dose", "Administration route", "Treatment duration", "Additional instructions", "Frecuency"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabPrescribeMedications);

        btnAdd.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnPrescribe.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnPrescribe.setText("Prescribe");
        btnPrescribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescribeActionPerformed(evt);
            }
        });

        cboApoointmentID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboApoointmentID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblAppointmentID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboApoointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(lblMedicationName))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblTreatmentDuration)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTreatmentDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblAdditionalInstructions)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAdditionalInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFrecuency)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFrecuency, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtMedicationName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDose)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDose, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblAdministrationRoute)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAdministrationRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(583, 583, 583)
                        .addComponent(btnPrescribe)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppointmentID)
                    .addComponent(lblMedicationName)
                    .addComponent(txtMedicationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDose)
                    .addComponent(txtDose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdministrationRoute)
                    .addComponent(txtAdministrationRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(cboApoointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTreatmentDuration)
                    .addComponent(txtTreatmentDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdditionalInstructions)
                    .addComponent(txtAdditionalInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFrecuency)
                    .addComponent(txtFrecuency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnPrescribe)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tabAppointments.addTab("Prescribe medications", jPanel2);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabAppointments))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabAppointments))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnXActionPerformed

    private void radioPendingAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPendingAppActionPerformed
        // TODO add your handling code here:
        radTotalApp.setSelected(false);
        Doctor d = (Doctor) user;
        DefaultTableModel model = (DefaultTableModel) tableTotalApp.getModel();
        model.setRowCount(0);
        for (Appointment a : d.getAppointments()) {
            if (a.getStatus().equals(AppointmentStatus.PENDING)) {
                model.addRow(new Object[]{a.getId(), a.getDatetime().toString(), a.getPatient().getFirstname() + " " + a.getDoctor().getLastname(), a.getSpecialty().name(), a.isType() ? "In person" : "Virtual", a.getStatus().name()});
            }
        }
    }//GEN-LAST:event_radioPendingAppActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String firstname = txtFirstname.getText();
        String lastname = txtLastname.getText();
        String spec = cboSpecialty.getItemAt(cboSpecialty.getSelectedIndex());
        String licenseNumber = txtLicenseNumber.getText();
        String assignedOffice = txtAssignedOffice.getText();
        String username = txtUser.getText();
        String password = txtPassword.getText();
        String comPassword = txtPasswordConfirm.getText();
        Specialty specialty = Specialty.valueOf(spec.replaceAll(" &", "").replaceAll(" ", "_"));
        if (password.equals(comPassword)) {
            for(User doc: this.users){
                if (doctor.getId() == doc.getId()) {
                    doctor.setFirstname(firstname);
                    doctor.setLastname(lastname);
                    doctor.setPassword(password);
                    doctor.setUsername(username);
                    doctor.setAssignedOffice(assignedOffice);
                    doctor.setLicenceNumber(licenseNumber);
                    doctor.setSpecialty(specialty);
                    
                }
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        NewJFrame login = new NewJFrame();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void lblBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBackActionPerformed
        NewJFrame11 admin = new NewJFrame11(user,users,hospitalizations, appointments);
        this.setVisible(false);
        admin.setVisible(true);
    }//GEN-LAST:event_lblBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (radRequests.isSelected()) {
            for(Hospitalization hosp : this.hospitalizations){
                if (cboRequests.getItemAt(cboRequests.getSelectedIndex()) == hosp.getId()) {
                    hosp.setStatus(HospitalizationStatus.CANCELED);
                }
            }
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        if (radPatientID.isSelected()) {
            for(User user: this.users){
                if (user instanceof Patient) {
                    if (cboPatientID.getItemAt(cboPatientID.getSelectedIndex()).equals(user.getId())) {
                        if (this.user instanceof Administrator) {
                            String reason = txtaRFHospitalization.getText();
                            String observations = txtaObservations2.getText();
                            String entDate = txtDateOfEntry.getText();
                            LocalDate entryDate = LocalDate.of(Integer.parseInt(entDate.substring(0, 4)), Integer.parseInt(entDate.substring(5, 7)), Integer.parseInt(entDate.substring(8)));
                            this.hospitalizations.add(new Hospitalization("asdfasdf", (Patient)user, this.doctor, LocalDate.MAX, reason, RoomType.IMC, observations, HospitalizationStatus.ONGOING));
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Patient p = null;
        for (User u : this.users) {
            if (u.getId() == Long.parseLong(cboPatient.getItemAt(cboPatient.getSelectedIndex()))) {
                p = (Patient) u;
            }
        }
        
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        for (Appointment a : p.getAppointments()) {
            model.addRow(new Object[]{a.getId(), a.getDatetime().toString(), a.getDoctor().getFirstname() + " " + a.getDoctor().getLastname(), a.getSpecialty().name(), a.isType() ? "In-person" : "Remote", a.getStatus().name()});
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void radTotalAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTotalAppActionPerformed
        // TODO add your handling code here:
        radioPendingApp.setSelected(false);
        Doctor d = (Doctor) user;
        DefaultTableModel model = (DefaultTableModel) tableTotalApp.getModel();
        model.setRowCount(0);
        for (Appointment a : d.getAppointments()) {
            model.addRow(new Object[]{a.getId(), a.getDatetime().toString(), a.getPatient().getFirstname() + " " + a.getDoctor().getLastname(), a.getSpecialty().name(), a.isType() ? "In-person" : "Remote", a.getStatus().name()});
        }
    }//GEN-LAST:event_radTotalAppActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        String idAppointment = cboAppID.getItemAt(cboAppID.getSelectedIndex());
        for(Appointment apo: this.appointments){
            if(apo.getId() == idAppointment){
                apo.setStatus(AppointmentStatus.PENDING);
            }
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        String idAppointment = cboAppointment2.getItemAt(cboAppointment2.getSelectedIndex());
        String diagnosis = txtaDiagnosis.getText();
        String observations = txtaObservations.getText();
        String recommendedTrea = txtaRT.getText();
        String followUp = txtaFuIndication.getText();
        for(Appointment apo: this.appointments){
            if(apo.getId() == idAppointment){
                apo.setStatus(AppointmentStatus.CANCELED);
                apo.setDiagnosis(diagnosis);
                apo.setFollowUp(followUp);
                apo.setRecommendedTreatment(recommendedTrea);
                apo.setObservations(observations);
            }
        }
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void btnPrescribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescribeActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabPrescribeMedications.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnPrescribeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabPrescribeMedications.getModel();
        
        String appointmentId = cboApoointmentID.getItemAt(cboApoointmentID.getSelectedIndex());
        String medicationName = txtMedicationName.getText();
        double dose = Double.parseDouble(txtDose.getText());
        String administrationRoute = txtAdministrationRoute.getText();
        int tratementduration = Integer.parseInt(txtTreatmentDuration.getText());
        String aditionalIformation = txtAdditionalInstructions.getText();
        int frecuency = Integer.parseInt(txtFrecuency.getText());
        
        model.addRow(new Object[]{appointmentId, medicationName, txtDose.getText(), administrationRoute, "" + tratementduration, aditionalIformation, "" + frecuency});
        for(Appointment apo: this.appointments){
            if (apo.getId().equals(appointmentId)){
                apo.addPrescription(new Prescription(apo, medicationName, dose, administrationRoute, tratementduration, aditionalIformation, frecuency));
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAccept2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccept2ActionPerformed
        String appointmentId = cboAppointment.getItemAt(cboAppointment.getSelectedIndex());
        Appointment appointment = null;
        for(Appointment apo: this.appointments){
            if (apo.getId().equals(appointmentId)) {
                appointment = apo;
            }
        }
        appointment.getDatetime().with(LocalTime.of(Integer.parseInt(txtNewTimeApp.getText().substring(0, 2)),Integer.parseInt(txtNewTimeApp.getText().substring(3))));
        String reasonChangeTime = txtReasonForApp.getText();
        appointment.setReason(reasonChangeTime);
    }//GEN-LAST:event_btnAccept2ActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAccept2;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnPrescribe;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnX;
    private javax.swing.JComboBox<String> cboApoointmentID;
    private javax.swing.JComboBox<String> cboAppID;
    private javax.swing.JComboBox<String> cboAppointment;
    private javax.swing.JComboBox<String> cboAppointment2;
    private javax.swing.JComboBox<String> cboPatient;
    private javax.swing.JComboBox<String> cboPatientID;
    private javax.swing.JComboBox<String> cboRequests;
    private javax.swing.JComboBox<String> cboSpecialty;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblAMA;
    private javax.swing.JLabel lblAdditionalInstructions;
    private javax.swing.JLabel lblAdministrationRoute;
    private javax.swing.JLabel lblAppID;
    private javax.swing.JLabel lblAppointment;
    private javax.swing.JLabel lblAppointment2;
    private javax.swing.JLabel lblAppointmentID;
    private javax.swing.JLabel lblAssignedOffice;
    private javax.swing.JButton lblBack;
    private javax.swing.JLabel lblCMA;
    private javax.swing.JLabel lblDateofEntry;
    private javax.swing.JLabel lblDiagnosis;
    private javax.swing.JLabel lblDoctorView;
    private javax.swing.JLabel lblDose;
    private javax.swing.JLabel lblEstimatedDuration;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblFrecuency;
    private javax.swing.JLabel lblFuIndication;
    private javax.swing.JLabel lblHospitalization;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblMedicationName;
    private javax.swing.JLabel lblNewTimeApp;
    private javax.swing.JLabel lblObservations;
    private javax.swing.JLabel lblObservations2;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordConfirm;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblRFHospitalization;
    private javax.swing.JLabel lblRMA;
    private javax.swing.JLabel lblRT;
    private javax.swing.JLabel lblReasonForApp;
    private javax.swing.JLabel lblSpecialty;
    private javax.swing.JLabel lblTreatmentDuration;
    private javax.swing.JLabel lblUser;
    private packagee.PanelRound panelRound1;
    private packagee.PanelRound panelRound2;
    private javax.swing.JRadioButton radPatientID;
    private javax.swing.JRadioButton radRequests;
    private javax.swing.JRadioButton radTotalApp;
    private javax.swing.JRadioButton radioPendingApp;
    private javax.swing.JTabbedPane tabAppointments;
    private javax.swing.JTable tabPrescribeMedications;
    private javax.swing.JTable tableTotalApp;
    private javax.swing.JTextField txtAdditionalInstructions;
    private javax.swing.JTextField txtAdministrationRoute;
    private javax.swing.JTextField txtAssignedOffice;
    private javax.swing.JTextField txtDateOfEntry;
    private javax.swing.JTextField txtDose;
    private javax.swing.JTextField txtEstimatedDuration;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtFrecuency;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtMedicationName;
    private javax.swing.JTextField txtNewTimeApp;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPasswordConfirm;
    private javax.swing.JTextField txtReasonForApp;
    private javax.swing.JTextField txtTreatmentDuration;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextArea txtaDiagnosis;
    private javax.swing.JTextArea txtaFuIndication;
    private javax.swing.JTextArea txtaObservations;
    private javax.swing.JTextArea txtaObservations2;
    private javax.swing.JTextArea txtaRFHospitalization;
    private javax.swing.JTextArea txtaRT;
    // End of variables declaration//GEN-END:variables
}
